website_project/website/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^squad/$', views.SquadView.as_view(), name='squad'),
    url(r'^gallery/$', views.GalleryView.as_view(), name='gallery'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostEditView.as_view(), name='post_edit'),
    url(r'^draft/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/delete/$', views.PostDeleteView.as_view(), name='post_delete'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment, name='add_comment'),
    # url(r'^comment/(?P<pk>\d+)/approve/$', views.approve_comment, name='approve_comment'),
    url(r'^comment/(?P<pk>\d+)/edit/$', views.CommentEditView.as_view(), name='edit_comment'),
    url(r'^comment/(?P<pk>\d+)/delete/$', views.delete_comment, name='delete_comment'),
    url(r'^matches/$', views.MatchesView.as_view(), name='matches'),
    url(r'^reset-season/$', views.ResetTeamSeason.as_view()),
    url(r'^table/$', views.TableView.as_view(), name='table'),
    url(r'^stats/$', views.StatsView.as_view(), name='stats'),
]

website_project/website_project/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'', include('website.urls')),
    # url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website_project/website/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('website.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=64)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self):
        return self.text


class Season(models.Model):
    name = models.CharField(max_length=32)
    start_year = models.PositiveSmallIntegerField()
    end_year = models.PositiveSmallIntegerField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Round(models.Model):
    name = models.CharField(max_length=32)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Team(models.Model):
    logo = models.FileField()
    logo_icon = models.FileField()
    name = models.CharField(max_length=64)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Match(models.Model):
    team_home = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="team_home")
    team_away = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="team_away")
    score_home = models.PositiveSmallIntegerField(null=True, blank=True)
    score_away = models.PositiveSmallIntegerField(null=True, blank=True)
    round = models.ForeignKey(Round, on_delete=models.CASCADE)

    def __str__(self):
        if self.score_home is not None and self.score_away is not None:
            return self.team_home.name + "-" + self.team_away.name + " " + str(self.score_home) + ":" + str(self.score_away)
        else:
            return self.team_home.name + "-" + self.team_away.name + " -:- "

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.score_home is not None and self.score_away is not None:
            ts_home = self.team_home.teamseason_set.filter(season__is_active=True).first()
            ts_away = self.team_away.teamseason_set.filter(season__is_active=True).first()

            ts_home.matches = ts_home.matches + 1
            ts_away.matches = ts_away.matches + 1
            ts_home.goals_for += self.score_home
            ts_away.goals_for += self.score_away
            ts_home.goals_against += self.score_away
            ts_away.goals_against += self.score_home

            if self.score_home > self.score_away:
                ts_home.wins += 1
                ts_away.losts += 1
                ts_home.points += 3

            if self.score_home < self.score_away:
                ts_home.losts += 1
                ts_away.wins += 1
                ts_away.points += 3

            if self.score_home == self.score_away:
                ts_home.draws += 1
                ts_away.draws += 1
                ts_home.points += 1
                ts_away.points += 1

            ts_home.save()
            ts_away.save()


class TeamSeason(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    matches = models.PositiveSmallIntegerField()
    wins = models.PositiveSmallIntegerField()
    draws = models.PositiveSmallIntegerField()
    losts = models.PositiveSmallIntegerField()
    goals_for = models.PositiveSmallIntegerField()
    goals_against = models.PositiveSmallIntegerField()
    points = models.SmallIntegerField()

    def __str__(self):
        return self.team.name


class Player(models.Model):
    number = models.PositiveSmallIntegerField()
    name = models.CharField(max_length=32)
    surname = models.CharField(max_length=32)
    position = models.CharField(max_length=32)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name + " " + self.surname


class PlayerStats(models.Model):
    appearances = models.PositiveSmallIntegerField(null=True)
    goals = models.PositiveSmallIntegerField(null=True)
    conceded = models.PositiveSmallIntegerField(null=True)
    clean_sheets = models.PositiveSmallIntegerField(null=True)
    assists = models.PositiveSmallIntegerField(null=True)
    yellow_cards = models.PositiveSmallIntegerField(null=True)
    red_cards = models.PositiveSmallIntegerField(null=True)
    minutes = models.PositiveSmallIntegerField(null=True)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)

    def __str__(self):
        return self.player.name + " " + self.player.surname

website_project/website/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author', 'title', 'text',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

        labels = {
            'author': "Autor",
            'title': "Tytuł newsa",
            'text': "Treść newsa"
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

        widgets = {
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor'}),
        }

        labels = {
            'author': "Autor",
            'text': "Treść komentarza"
        }

website_project/website/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import View

from .models import Post, Comment, Player, Match, TeamSeason, Team, Season, PlayerStats
from .forms import PostForm, CommentForm


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'website/post_detail.html'

    form_class = PostForm

    model = Post


class PostEditView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'website/post_detail.html'

    form_class = PostForm

    model = Post


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'website/post_list.html'
    template_name = 'website/post_draft_list.html'

    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)


# @login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            comment.approve()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'website/comment_form.html', {'form': form})


# @login_required
# def approve_comment(request, pk):
#     comment = get_object_or_404(Comment, pk=pk)
#     comment.approve()
#     return redirect('post_detail', pk=comment.post.pk)

class CommentEditView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'website/post_detail.html'

    form_class = CommentForm

    model = Comment


@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail', pk=post_pk)


class AboutView(TemplateView):
    template_name = 'about.html'


class GalleryView(TemplateView):
    template_name = 'gallery.html'


class ContactView(TemplateView):
    template_name = 'contact.html'


class SquadView(ListView):
    model = Player

    def get_queryset(self):
        return Player.objects.all().order_by('number')


class MatchesView(ListView):
    model = Match

    def get_queryset(self):
        return Match.objects.order_by('round__id', 'id')


class ResetTeamSeason(View):
    def get(self, request):
        TeamSeason.objects.all().delete()

        for season in Season.objects.all():
            for team in Team.objects.all():
                TeamSeason.objects.create(team=team,
                                          season=season,
                                          matches=0,
                                          wins=0,
                                          draws=0,
                                          losts=0,
                                          goals_for=0,
                                          goals_against=0,
                                          points=0
                                          )
        for match in Match.objects.all():
            match.save()
        return HttpResponse("OK")


class TableView(ListView):
    model = TeamSeason

    def get_queryset(self):
        return TeamSeason.objects.all().order_by('-points')


class StatsView(ListView):
    model = PlayerStats

    def get_queryset(self):
        return PlayerStats.objects.all().order_by('player__number')

website_project/website/templates/website/about.html
{% extends "website/base.html" %}
{% block content %}

<h1 class="menu-h">O klubie</h1>
<h3 class="menu-h">Klub Sportowy Jutrzenka Cegłów</h3>
<h3><strong>Rok założenia:</strong> 1936</h3>
<h3><strong>Barwy:</strong> niebiesko-biało-czerwone</h3>
<h3><strong>Najwyższy poziom ligowy:</strong> IV liga</h3>
<h3><strong>Prezes:</strong> Przemysław Kaczorek</h3>
<h3><strong>Trener:</strong> Sławomir Słodownik</h3>

{% endblock %}

website_project/website/templates/website/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pl">
    <head>
        <meta charset="UTF-8"/>
        <title>Jutrzenka Cegłów - oficjalna strona</title>
        <meta name="description" content="Jutrzenka Cegłów - oficjalna strona drużyny piłkarskiej. Aktualności z klubu, wyniki meczów, tabele i statystyki. Zapraszamy do przeglądania i komentowania!"/>
        <meta name="keywords" content="Jutrzenka, Cegłów, klub piłkarski, drużyna piłkarska"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">

        <!-- Medium Editor -->
        <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/website.css' %}">

        <!--Icon-->
        <link rel="shortcut icon" href="{% static 'img/jutrzenka_icon.ico' %}" type="image/x-icon">
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    </head>

    <body>
        <div class="page-header">
            <h1><a href="{% url 'post_list' %}"><img src="{% static 'img/jutrzenka.png' %}" alt="logo"> Jutrzenka Cegłów</a></h1>
        </div>

        <nav class="navbar navbar-default menu">
            <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'post_list' %}">Strona główna</a></li>
                        <li><a href="{% url 'squad' %}">Kadra</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sezon <span class="caret"></span></a>
                            <ul class="dropdown-menu dropdown">
                                <li><a href="{% url 'matches' %}">Terminarz i wyniki rozgrywek</a></li>
                                <li><a href="{% url 'table' %}">Tabela</a></li>
                                <li><a href="{% url 'stats' %}">Statystyki zawodników</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'gallery' %}">Galeria</a></li>
                        <li><a href="{% url 'about' %}">O klubie</a></li>
                        <li><a href="{% url 'contact' %}">Kontakt</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li>
                            <a>Witaj, {{ user.username }}!</a>
                        </li>
                        <li>
                            <a href="{% url 'post_new' %}" >Nowy post</a>
                        </li>
                        <li>
                            <a href="{% url 'post_draft_list' %}">Wersje robocze</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}" >Wyloguj się</a>
                        </li>
                    {% comment %}{% else %}
                        <li>
                          <a class='nav navbar-right' href="{% url 'login' %}">
                              <span class="glyphicon glyphicon-user"></span>
                          </a>
                        </li>
                    {% endcomment %}
                    {% endif %}

                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

        <div class="content container">
            <div class="row">
                <div class="col-md-7">
                    <div>
                    {% block content %}

                    {% endblock %}
                    </div>

                </div>
                <div class="col-md-1">

                </div>

                <div class="col-md-4">
                    <div class="match-info">
                        <p>Ostatni mecz</p>
                        <p><img src="{% static 'img/info_logo_jastrzab_zeliszew.png' %}" alt="logo1">3:1<img src="{% static 'img/info_logo_jutrzenka_ceglow.png' %}" alt="logo2"></p>
                        <p class="match-info-date">13 maja 2018r., godz. 17:00, Żeliszew</p><hr>
                        <p>Następny mecz</p>
                        <p><img src="{% static 'img/info_logo_jutrzenka_ceglow.png' %}" alt="logo1">-:-<img src="{% static 'img/info_logo_polonez_mordy.png' %}" alt="logo2"></p>
                        <p class="match-info-date">19 maja 2018r., godz. 11:00, Cegłów</p>
                        <hr>
                    </div>
                {% block table %}
                    <div class="table-responsive-md">
                        <table class="table">
                            <p class="table-title">Tabela rozgrywek</p>
                            <thead>
                                <tr>
                                <th>#</th>
                                <th>Drużyna</th>
                                <th>Mecze</th>
                                <th>Punkty</th>
                                </tr>
                            </thead>

                            {% for teamseason in teamseason_list %}
                            <tbody>
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td><img src="{{ teamseason.team.logo_icon.url }}" /> {{ teamseason.team.name }}</td>
                                    <td>{{ teamseason.matches }}</td>
                                    <td>{{ teamseason.points }}</td>
                                </tr>
                            </tbody>
                            {% endfor %}

                        </table>
                    </div>
                {% endblock %}
                    <div class="fanpage">
                        <a href="https://www.facebook.com/KS-Jutrzenka-Ceg%C5%82%C3%B3w-282845598403885/" target="_blank"><p class="fanpage-icon"><img src="{% static 'img/fb.PNG' %}" alt="fanpage"></p></a>
                        <!--<hr>-->
                    </div>

                    <div class="sponsors">
                        <p class="sponsors-header">Sponsorzy:</p>
                        <a href="https://ceglow.pl/" target="_blank"><p class="gmina-icon"><img src="{% static 'img/gmina.PNG' %}" alt="gmina"></p></a>
                        <a href="http://www.bags.com.pl/" target="_blank"><p class="bags-icon"><img src="{% static 'img/bags.PNG' %}" alt="bags"></p></a>
                        <a href="https://panoramafirm.pl/mazowieckie,mi%C5%84ski,ceg%C5%82%C3%B3w,orzeszkowej,8/autopex_lukasz_pernach_mechanika_pojazdowa-aiwdob_prt.html" target="_blank"><p class="autopex-icon"><img src="{% static 'img/autopex.PNG' %}" alt="autopex"></p></a>
                    </div>

                </div>

            </div>
        </div>

        <nav class="navbar navbar-default navbar-fixed-bottom footer-style">
            <div class="container footer-style">
                <span class="text-muted">jutrzenkaceglow.pl &copy; 2018 Wszelkie prawa zastrzeżone. Projekt i realizacja: Eryk Malinowski
                    <a href="https://github.com/ErykMalinowski" target="_blank"><i class="fab fa-github fa-lg github-color"></i></a>
                    <a href="https://www.linkedin.com/in/eryk-malinowski/" target="_blank"><i class="fab fa-linkedin fa-lg linkedin-color"></i></a>
                    <a href="https://www.codewars.com/users/ErykMalinowski" target="_blank"><img src="{% static 'img/codewars_logo.png' %}"></a>
                </span>
            </div>
        </nav>

    <a href="#"><img src="{% static 'img/up_icon.png' %}" class="scroll-top"></a>

    <script type="text/javascript" src="{% static 'js/website.js' %}"></script>

    </body>
</html>

website_project/website/templates/website/comment_form.html
{% extends "website/base.html" %}
{% block content %}

<h2>Nowy komentarz</h2>

<form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-default btn-comment-publish">Dodaj komentarz</button>
</form>

<script>var editor = new MediumEditor('.editable', {
    placeholder: {
        text: 'Kliknij i wpisz, co chcesz! (wskazówka -> zaznaczając tekst, możesz go edytować)',
        hideOnClick: true
    }
});</script>

{% endblock %}

website_project/website/templates/website/contact.html
{% extends "website/base.html" %}
{% block content %}
<h1 class="menu-h">Kontakt</h1>
<h3>Znajdziesz nas na Facebook'u -
    <a href="https://www.facebook.com/KS-Jutrzenka-Ceg%C5%82%C3%B3w-282845598403885/" target="_blank"><i class="fab fa-facebook-f fa-lg"></i></a>
</h3>

{% endblock %}

website_project/website/templates/website/gallery.html
{% extends "website/base.html" %}
{% block content %}
{% load staticfiles %}

<h1 class="menu-h-gallery">Galeria</h1>

<div id="myCarousel" class="carousel slide" data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
        <li data-target="#myCarousel" data-slide-to="5"></li>
    </ol>


    <div class="carousel-inner">
        <div class="item active">
            <img src="{% static 'img/image1.jpg' %}" alt="Obrazek nr 1">
        </div>

        <div class="item">
            <img src="{% static 'img/image2.jpg' %}" alt="Obrazek nr 2">
        </div>

        <div class="item">
            <img src="{% static 'img/image3.jpg' %}" alt="Obrazek nr 3">
        </div>

        <div class="item">
            <img src="{% static 'img/image4.jpg' %}" alt="Obrazek nr 4">
        </div>

        <div class="item">
            <img src="{% static 'img/image5.jpg' %}" alt="Obrazek nr 5">
        </div>

        <div class="item">
            <img src="{% static 'img/image6.jpg' %}" alt="Obrazek nr 6">
        </div>
    </div>


    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Poprzedni</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Następny</span>
    </a>
</div>

{% endblock %}

website_project/website/templates/website/match_list.html
{% extends "website/base.html" %}
{% block content %}

<h1 class="menu-h">Terminarz i wyniki rozgrywek</h1>

{% regroup match_list by round as rounds %}
{% for round in rounds %}
    <h3>{{ round.grouper.name }}</h3>
    <div class="post">
        {% for match in round.list %}
            {% if match.score_home != None and match.score_away != None %}
            <div>
                <p>{{ match.team_home }} <img src="{{ match.team_home.logo_icon.url }}"> {{ match.score_home }}:{{ match.score_away }} <img src="{{ match.team_away.logo_icon.url }}"> {{ match.team_away }}</p>
            </div>
            {% else %}
            <div>
                <p>{{ match.team_home }} <img src="{{ match.team_home.logo_icon.url }}"> -:- <img src="{{ match.team_away.logo_icon.url }}"> {{ match.team_away }}</p>
            </div>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}

{% endblock %}

website_project/website/templates/website/player_list.html
{% extends "website/base.html" %}
{% block content %}

<h1 class="squad-h1">Kadra w sezonie 2017/18</h1>
<h2 class="squad-h2">Bramkarze:</h2>

{% for player in player_list %}
    {% if player.position == 'bramkarz' %}
        <div class="post squad">
            <div>
                <p>#{{ player.number }} {{ player.name }} {{ player.surname }}</p>
            </div>
        </div>
    {% endif %}
{% endfor %}

<h2 class="squad-h2">Obrońcy:</h2>

{% for player in player_list %}
    {% if player.position == 'obrońca' %}
        <div class="post squad">
            <div>
                <p>#{{ player.number }} {{ player.name }} {{ player.surname }}</p>
            </div>
        </div>
    {% endif %}
{% endfor %}

<h2 class="squad-h2">Pomocnicy:</h2>

{% for player in player_list %}
    {% if player.position == 'pomocnik' %}
        <div class="post squad">
            <div>
                <p>#{{ player.number }} {{ player.name }} {{ player.surname }}</p>
            </div>
        </div>
    {% endif %}
{% endfor %}

<h2 class="squad-h2">Napastnicy:</h2>

{% for player in player_list %}
    {% if player.position == 'napastnik' %}
        <div class="post squad">
            <div>
                <p>#{{ player.number }} {{ player.name }} {{ player.surname }}</p>
            </div>
        </div>
    {% endif %}
{% endfor %}

{% endblock %}

website_project/website/templates/website/post_confirm_delete.html
{% extends "website/base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Czy na pewno chcesz usunąć wpis "{{ object }}"?</p>
    <input class='btn btn-danger' type="submit" value="Potwierdź" />
</form>

{% endblock %}